### ISSUE TITLE
The question about pcb

### ISSUE THREAD

**Issue by HellbroWDR** [ravinrabbid/DonCon2040#1]
I am very interesting in your projects of arcade taiko and want to make one. Could you teach me how to get the pcb you use to this project？

**Comment by ravinrabbid** [comment]
You can find the pcbs in the pcb subfolder. Those are KiCad projects (you might need a recent nightly build of Kicad to open them). How to properly export the data necessary for manufacturing depends on the manufacturer you want to use. This I'm afraid you'll have to research this yourself.
Regarding assembly I also can't help you much since I source the parts and solder the boards myself. I've noted the Digikey parts I used in the readme for reference. 

I'll be closing this, since it doesn't really belong into the Issues and would kindly ask you to use the Discussions section of the project for further questions like this.

**Comment by HellbroWDR** [comment]
I'm sorry for the wrong way to ask the question. Thank you for tolerant of my mistakes and taking your precious time to answer my questions.
