### ISSUE TITLE
PS4 Controller Emulation

### ISSUE THREAD

**Issue by mechachoi** [ravinrabbid/DonCon2040#5]
I have an arcade taiko that I'm trying to get to talk to a PS5 taiko game. I'm curious-- is there any way I could get this to talk to a PS5? I know that there are fighting game stick boards (e.g. P5 mini https://www.brookaccessory.com/detail/92299183/) that are compatible with PS5. 

Is there any idea how we might connect the output of this board to one of those to get PS5 functionality working?

**Comment by ravinrabbid** [comment]
Hi,

I don't know what "arcade taiko" you are using, but if you are talking about this project you could modify the firmware to toggle a GPIO pin when a hit is detected and connect this pin to the brooks board.

However, to my knowledge (which might be outdated and/or wrong) for PS5 compatibility the game itself must have "legacy controller support" which will allow it to work with licensed PS4 controllers. Most fighting games do this and I suppose that is the reason why the Brooks website states "PS5 (Fighting game)" compatibility (instead of just writing PS5).

Taiko on PS5 might has legacy controller support since an official PS4 Taiko Controller exists, but I wouldn't bet on it.

**Comment by mechachoi** [comment]
Awesome, thanks for the info! I just had the boards fabbed earlier this week and looking forward to bringing them up! Look forward to more questions...
